dist: xenial

addons:
  apt:
    packages:
      - ant-optional

language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - "nightly"

env:
  - CONTAO_VERSION=contao/core-bundle ~4.4.0
  - CONTAO_VERSION=contao/core-bundle ~4.9.0

matrix:
  allow_failures:
    - php: "nightly"

sudo: false

before_install:
  - echo "memory_limit = -1" > travis.php.ini && phpenv config-add travis.php.ini

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer require $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

git:
  depth: false

cache:
  directories:
    - vendor
