language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

env:
  - CONTAO_VERSION=contao/core-bundle ~4.4.0
  - CONTAO_VERSION=contao/core-bundle ~4.5.0
  - CONTAO_VERSION=contao/core-bundle ~4.6.0
  - CONTAO_VERSION=contao/core-bundle ~4.7.0
  - CONTAO_VERSION=contao/core-bundle ~4.8.0
  - CONTAO_VERSION=contao/core-bundle ~4.9.0

matrix:
  allow_failures:
    - php: "nightly"
    - env: CONTAO_VERSION=contao/core-bundle ~4.5.0
    - env: CONTAO_VERSION=contao/core-bundle ~4.6.0
    - env: CONTAO_VERSION=contao/core-bundle ~4.7.0
    - env: CONTAO_VERSION=contao/core-bundle ~4.8.0

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer require $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

git:
  depth: false

cache:
  directories:
    - vendor
